before_script:
  - psql -c 'create database search;'
  - psql -d search -c 'CREATE TABLE items (id text unique,product_name text);'
sudo: true
language: node_js
node_js:
  - 'stable'
script:
  - /Users/garyblaser/workspace/header-and-search/tests/init-db.sh
  - npm run test
cache:
 directories:
   - 'node_modules'
services:
 - postgresql