before_script:
  - psql -c 'create database postgres;'
  - psql -d postgres -c 'CREATE TABLE items (id text unique,product_name text);'
sudo: true
language: node_js
node_js:
  - 'stable'
script:
  - ./test/init-db.sh
  - npm run test
cache:
 directories:
   - 'node_modules'
services:
 - postgresql